### ISSUE TITLE
Aborted Recalls for a missing attribute in Phase2RetrieveDomainUsersHandler in the backend

### ISSUE THREAD

**Issue by mirons-google** [google/googleapps-message-recall#2]
'Phase2RetrieveDomainUsersHandler' object has no attribute '_was_incremented'
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/apps/s~message-recall-cfprod/recall-backend.381492479498808109/backend_views.py", line 216, in handle_exception
    if self._was_incremented:
AttributeError: 'Phase2RetrieveDomainUsersHandler' object has no attribute '_was_incremented'

**Comment by miketruty** [comment]
I was finally able to reproduce this as an artifact of using aliases.  The admin sdk user api returns users with aliases based on search criteria in addition to those who match primaryEmail.  I've adjusted for this and corrected a counter that reflects these unexpected returns when they occur.

**Comment by miketruty** [comment]
This is fixed per the push on 2015-10-28.
