### ISSUE TITLE
invalid_grant on first load

### ISSUE THREAD

**Issue by mirons-google** [google/googleapps-message-recall#3]
<code>
Example logs
D 2015-10-27 15:26:14.217

{'aud': 'https://accounts.google.com/o/oauth2/token', 'exp': 1445943374L, 'iat': 1445939774L, 'iss': 'XXX@developer.gserviceaccount.com', 'scope': 'https://www.googleapis.com/auth/admin.directory.user.readonly https://mail.google.com/', 'sub': 'xxx@searcelabs.com'}
D 2015-10-27 15:26:14.250

['eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9', 'eyJhdWQiOiJodHRwczovL2FjY291bnRzLmdvb2dsZS5jb20vby9vYXV0aDIvdG9rZW4iLCJleHAiOjE0NDU5NDMzNzQsImlhdCI6MTQ0NTkzOTc3NCwiaXNzIjoiNDc2NTg2MTMxNDk1LXZjZHExb2RpbWVzdTE4ZDNnZHZlNW9pMnRla2VsaHVhQGRldmVsb3Blci5nc2VydmljZWFjY291bnQuY29tIiwic2NvcGUiOiJodHRwczovL3d3dy5nb29nbGVhcGlzLmNvbS9hdXRoL2FkbWluLmRpcmVjdG9yeS51c2VyLnJlYWRvbmx5IGh0dHBzOi8vbWFpbC5nb29nbGUuY29tLyIsInN1YiI6InRlc3QxQHNlYXJjZWxhYnMuY29tIn0', 'HuTUfKXxMoHAj1Gbi2RHdkEtLjfEbZLiYymiGBhUEuKyQKUA0xhNPHhRiLwaGixWj_rM1tLmnysEHG00YPFV5-3dQFzsqNki21PJEsOJF7griDzhlWjrrCaSltcxyis-6dFALkCk2Fd4e5DV2rEOcF5rstTLdQ5Sxtb3SCJDH_TLtZfIEDF1ay3xkmy-En0wnM_rqG_DjfPTU2jDtwt1Cj4xjOh5Z6ms8vILZ6O8fLtQwPAsp1WahQfR4ZeyAGUyVLqs6FIv7opQUYDSyQyGX5pEschccmlar4n4njhSO8dFYkJlHwprhK7a_YauOcZtC4aiiQBIKQaoOCEGcINwwA']
I 2015-10-27 15:26:14.250

Refreshing access_token
I 2015-10-27 15:26:14.284

Failed to retrieve access token: {
  "error" : "invalid_grant"
}
E 2015-10-27 15:26:14.284

invalid_grant
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~searce-test-101/1.388141334937762057/frontend_views.py", line 411, in get
    _PreventUnauthorizedAccess()
  File "/base/data/home/apps/s~searce-test-101/1.388141334937762057/frontend_views.py", line 190, in _PreventUnauthorizedAccess
    _FailIfNonAdminUser(current_user_email)
  File "/base/data/home/apps/s~searce-test-101/1.388141334937762057/frontend_views.py", line 178, in _FailIfNonAdminUser
    search_query='email:%s' % user_email)
  File "/base/data/home/apps/s~searce-test-101/1.388141334937762057/user_retriever.py", line 48, in __init__
    self._http = credentials_utils.GetAuthorizedHttp(owner_email)
  File "/base/data/home/apps/s~searce-test-101/1.388141334937762057/credentials_utils.py", line 89, in GetAuthorizedHttp
    credentials.access_token = GetUserAccessToken(user_email)
  File "/base/data/home/apps/s~searce-test-101/1.388141334937762057/credentials_utils.py", line 111, in GetUserAccessToken
    credentials.refresh(http_utils.GetHttpObject())
  File "/base/data/home/apps/s~searce-test-101/1.388141334937762057/lib/oauth2client/client.py", line 516, in refresh
    self._refresh(http.request)
  File "/base/data/home/apps/s~searce-test-101/1.388141334937762057/lib/oauth2client/client.py", line 653, in _refresh
    self._do_refresh_request(http_request)
  File "/base/data/home/apps/s~searce-test-101/1.388141334937762057/lib/oauth2client/client.py", line 710, in _do_refresh_request
    raise AccessTokenRefreshError(error_msg)
AccessTokenRefreshError: invalid_grant
D 2015-10-27 15:26:14.285

Is the web application in debug mode? False.
D 2015-10-27 15:26:14.299

Handler for https://searce-test-101.appspot.com/ took 0.09 seconds
</code>

![0](https://cloud.githubusercontent.com/assets/3867367/10765073/1fb33324-7c9f-11e5-82b7-4a233dc2b5b7.png)

**Comment by miketruty** [comment]
I cannot recreate this.  Do we want to keep this open?
